# -*- mode: ruby -*-# -*- mode: ruby -*-

# vi: set ft=ruby :# vi: set ft=ruby :



# DNS Server VM Configuration# All Vagrant configuration is done below. The "2" in Vagrant.configure

Vagrant.configure("2") do |config|# configures the configuration version (we support older styles for

  # DNS Server box# backwards compatibility). Please don't change it unless you know what

  config.vm.box = "open_network_security/dns_server"# you're doing.

  config.vm.box_version = "1.0.0"Vagrant.configure("2") do |config|

  # The most common configuration options are documented and commented below.

  # Set up Internal Network for isolated VM-to-VM communication (VirtualBox specific)  # For a complete reference, please see the online documentation at

  # Assign a static IP address for this VM on the internal network  # https://docs.vagrantup.com.

  config.vm.network "private_network", ip: "192.168.10.1", virtualbox__intnet: "labnet"

  # Every Vagrant development environment requires a box. You can search for

  # VirtualBox provider configuration  # boxes at https://vagrantcloud.com/search.

  config.vm.provider "virtualbox" do |vb|  config.vm.box = "open_network_security/dns_server"

    # Display the VirtualBox GUI when booting the machine  config.vm.box_version = "1.0.0"

    vb.gui = true

  # Disable automatic box update checking. If you disable this, then

    # Customize the amount of memory on the VM:  # boxes will only be checked for updates when the user runs

    vb.memory = "4096"  # `vagrant box outdated`. This is not recommended.

    vb.cpus = 2  # config.vm.box_check_update = false

  end

end 
