---
- name: Configure Detective resolver to use DNS VM
  hosts: detective
  become: yes
  tasks:
    - name: Backup current resolv.conf
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.backup
        remote_src: yes
        backup: yes

    - name: Set DNS server to 192.168.10.1
      copy:
        dest: /etc/resolv.conf
        content: |-
          nameserver 192.168.10.1
          search uni.lux
        owner: root
        group: root
        mode: '0644'

    - name: Verify DNS resolution
      command: nslookup google.com 192.168.10.1
      register: nslookup_out
      ignore_errors: yes

    - name: Show nslookup result
      debug:
        var: nslookup_out.stdout
