# -*- mode: ruby -*-
# vi: set ft=ruby :

# Detective VM Configuration
# This VM connects to the internal network of the DNS server
Vagrant.configure("2") do |config|
  # Base box for the detective - use official Ubuntu Jammy for simplicity
  config.vm.box = "bento/ubuntu-22.04"

  # Synced folders
  # On Windows (using ansible_local), we need /vagrant synced for playbook access
  # On Linux/macOS (using host ansible), we can disable it for better isolation
  if Vagrant::Util::Platform.windows?
    # Keep default /vagrant sync enabled for ansible_local
  else
    # Disable default synced folder for better isolation
    config.vm.synced_folder ".", "/vagrant", disabled: true
  end

  # Connect to the same internal network as the DNS server
  # This will put the agent on the same network as the DNS server (192.168.10.1)
  # The agent will get an IP from the DHCP server (192.168.10.3-192.168.10.100)
  config.vm.network "private_network", 
                    type: "dhcp", 
                    virtualbox__intnet: "labnet"

  # Alternative: Assign a static IP if you prefer (uncomment the line below and comment the DHCP line above)
  # config.vm.network "private_network", ip: "192.168.10.10", virtualbox__intnet: "labnet"

  # VirtualBox provider configuration
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    
    # Customize the amount of memory on the VM
    vb.memory = "2048"
    
    # Set the number of CPUs on the VM
    vb.cpus = 2
    
    # Set VM name
    vb.name = "detective-vm"
  end

  # Provision Detective VM using Ansible
  # On Windows: use ansible_local (runs Ansible inside the VM)
  # On Linux/macOS: use ansible (runs from host)
  if Vagrant::Util::Platform.windows?
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/vagrant/detective-playbook.yml"
      ansible.groups = { 'detective' => ['default'] }
      ansible.install = true
      ansible.install_mode = :pip
      ansible.pip_install_cmd = "curl https://bootstrap.pypa.io/get-pip.py | sudo python3"
    end
  else
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "./detective-playbook.yml"
      ansible.groups = { 'detective' => ['default'] }
    end
  end
end