# -*- mode: ruby -*-
# vi: set ft=ruby :

# Detective VM Configuration
# This VM connects to the internal network of the DNS server
Vagrant.configure("2") do |config|
  # Base box for the detective - use official Ubuntu Jammy for simplicity
  config.vm.box = "ubuntu/jammy64"

  # Disable default synced folder for better isolation
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Connect to the same internal network as the DNS server
  # This will put the agent on the same network as the DNS server (192.168.10.1)
  # The agent will get an IP from the DHCP server (192.168.10.3-192.168.10.100)
  config.vm.network "private_network", 
                    type: "dhcp", 
                    virtualbox__intnet: "labnet"

  # Alternative: Assign a static IP if you prefer (uncomment the line below and comment the DHCP line above)
  # config.vm.network "private_network", ip: "192.168.10.10", virtualbox__intnet: "labnet"

  # VirtualBox provider configuration
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    
    # Customize the amount of memory on the VM
    vb.memory = "2048"
    
    # Set the number of CPUs on the VM
    vb.cpus = 2
    
    # Set VM name
    vb.name = "detective-vm"
  end

  # Provisioning script to configure the agent
  # Provision Detective VM using Ansible to set resolver (mirrors Agent)
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./detective-playbook.yml"
    ansible.groups = { 'detective' => ['default'] }
    # Use Vagrant-generated inventory (do not set inventory_path)
  end
end